import Head from "next/head";
import { Inter } from "next/font/google";
import { GET } from "@/utils/HTTP";
import Hero from "../components/hero/Hero";
import Cards from "@/components/Cards/Cards";
import styles from "@/styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ trending, pippo }) {
  // console.log(trending)
  // console.log(pippo)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Cards data={trending} />
        <Cards data={trending} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const trending = await GET("trending/movie/", "day");
  const pippo = await GET("search/", "movie", "", "barbie");

  return {
    props: {
      trending,
      pippo,
    },
  };
}
