import { GET } from "@/utils/HTTP";
import { useRouter } from "next/router";
import Head from "next/head";
import Card from "@/components/Card/Card";
import styles from "@/styles/searchedMovieGrid.module.scss";

export default function searchResult({ data }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Search results for "{router.query.searchedMovie}"</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.searchedMovie}>
        <h1 className={styles.searchTitle}>
          Search results for "{router.query.searchedMovie}"
        </h1>
        <div className={styles.searchResult}>
          {data.results.map((movie, i) => (
            <Card mock={movie} key={i} />
          ))}
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps(router) {
  const data = await GET("search/", "movie", "", router.query.searchedMovie);

  return {
    props: {
      data,
    },
  };
}
